import Head from 'next/head'
import { Inter } from '@next/font/google'

import { Box, Button, Flex,  Heading,Image, SimpleGrid, Text } from '@chakra-ui/react'
import { BiGitRepoForked } from "react-icons/bi";
import { ImStarEmpty } from "react-icons/im";
const inter = Inter({ subsets: ['latin'] })

export default function Home({profile, project}) {
  
  return (
    <>
      <Head>
        <title>rashmi-portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Flex w={"97%"} m="auto" gap={"20px"}>
            <Flex  w="25%" gap={"10px"} flexDir="column">
              <Flex boxShadow='base' rounded={"xl"} flexDir={"column"} gap="20px"  alignItems={"center"} p="20px">
                  <Image src={profile.avatar_url} w={"100px"} h="100px" borderRadius={"50%"} alt="Rashmi" />
                  <Heading as='h4' size='md'>{profile.name}</Heading>
                  <Text fontWeight={"bold"} color={"gray.500"} fontSize='sm'>@{profile.login}</Text>
                  <Text textAlign={"center"} fontSize='md'>{profile.bio}</Text>
                  <SimpleGrid columns={[1,1,2]} gap="16px">
                    <a href='https://drive.google.com/file/d/1EuE98MfT2Z4s4wxcnEa4c4Jk-Irgt9R2/view?usp=sharing'>
                     <Button bg={"green.400"} color="white" px={"40px"} rounded="full" >Resume</Button>
                    </a>
                    <a href='https://github.com/mukeshsahu1997'>
                       <Button bg={'blue.400'} color="white" px={"40px"}  rounded="full" >Follow</Button>
                    </a>
                  </SimpleGrid>

              </Flex>
              
              <SimpleGrid boxShadow='base' rounded={"xl"}  p="10px" gap={"10px"} columns={[2,3,3]} >
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>HTML</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>CSS</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>JAVASCRIPT</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>REACT JS</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>REDUX</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>TYPESCRIPT</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>NEXT JS</Button>
                  <Button bg={"teal.200"} color="gray.600" fontSize="sm" fontWeight={"bold"}>CHAKRA-UI</Button>
                 
              </SimpleGrid>
              <Box boxShadow='base' rounded={"xl"}  p="10px">
                <Heading textAlign={"center"} size="md" >Education</Heading>
               <Text  fontSize='sm' p={"5px"}>Full-Stack-Web Developement - Masai Banglore</Text>
               <Text  fontSize='sm' p={"5px"}>12th - Government Science College, Chatrapur</Text>
             
              </Box>
            </Flex>
         
          {/* project */}
             <Box boxShadow='base' w="75%">
              <Heading textAlign={"center"} size="xl" p="20px">Project</Heading>
              <SimpleGrid columns={[1,1,2]} w="98%" m={"auto"} gap="20px">
                  {
                    project.items.map((el)=>(
                      <a key={el.id} href={el.html_url}>
                        <Flex flexDir={"column"}  boxShadow='base' rounded={"xl"} p="20px" gap={"10px"}>
                          <Text fontSize={"lg"} fontWeight="semibold" color={"gray.800"}>{el.name}</Text>
                          <Text fontSize={"sm"}>{el.description}</Text>
                          <Flex justifyContent={"space-between"} alignItems="center">
                            <Flex gap={"30px"} >
                              <Flex gap="10px" alignItems={"center"}>
                                <ImStarEmpty/>
                              <Text fontWeight={"semibold"} fontSize="xl">{el.stargazers_count}</Text>
                             </Flex>
                              <Flex gap="10px" alignItems={"center"}>
                                <BiGitRepoForked/>
                              <Text fontWeight={"semibold"} fontSize="xl">{el.forks_count}</Text>
                              
                              </Flex>
                            </Flex>
                            <Text fontSize={"lg"} fontWeight="semibold" color={"gray.800"}>{el.language}</Text>
                          </Flex>
                        </Flex>
                      </a>
                    ))
                  }
              </SimpleGrid>
            </Box>
          </Flex>
        </Box>
      </main>
    </>
  )
}

export async function getStaticProps(){
  let res= await fetch(`https://api.github.com/users/mukeshsahu1997`)
  let res1=await fetch(`https://api.github.com/search/repositories?q=user:mukeshsahu1997+fork:true&sort=updated&per_page=10&type=Repositories`)
  let data=await res.json()
  let data1=await res1.json()
  return {
    props:{
      profile:data,
      project:data1
    }
  }
}